E cuadras 31 new feat medios de adquisicion
LyticaMx/apervox-frontend-blackhole pull request #34
Opened 2023-02-23 20:24 UTC by efracuadras

vista Medios de adquisicion

2023-02-23 20:28 UTC, Ghostramses approved these changes

2023-02-23 20:33 UTC, armandoalbor approved these changes

2023-02-23 20:49 UTC, JavierAlbor requested changes
Resolver comentarios

2023-02-23 20:49 UTC, JavierAlbor commented on src/views/Acquisition/messages.ts
> +  source: {
El mensaje esta repetido

2023-02-24 23:38 UTC, JavierAlbor approved these changes

2023-02-24 23:39 UTC, merged