E cuadras 67 new feat vista de tecnica
LyticaMx/apervox-frontend-blackhole pull request #70
Opened 2023-04-17 15:50 UTC by efracuadras

- Separación de la vista de técnicas
- Cambio de estilos en la vista de técnica

2023-04-17 16:38 UTC, JavierAlbor approved these changes

2023-04-17 16:38 UTC, JavierAlbor commented on src/context/Technique/actions.ts
> +  const setTechnique = (payload: Technique): void => {
Seria bueno que tambien se agreguen cleaners dentro de cada acción

if (prop) dispatch(initialState)

2023-04-17 16:38 UTC, JavierAlbor commented on src/layout/BaseLayout.tsx
> +              <div className="mx-auto px-4 sm:px-6 md:px-8 py-4">
Pienso que si no trabajaremos de lleno el responsive, seria mejor quitar cualquier breakpoint dentro de los componentes para evitar confuisones en el futuro

2023-04-17 16:38 UTC, JavierAlbor commented on src/views/Technique/components/CreateObjectiveDialog.tsx
En el archivo de types se renombro objective => target
Considero que seria bueno realizar esto en todas las coincidencias. Por ejemplo, el nombre de este archivo "CreateObjectiveDialog"

2023-04-17 16:38 UTC, JavierAlbor commented on src/views/Technique/components/CreateObjectiveDialog.tsx
> +        <ObjectiveForm onSubmit={onAccept as any} />
Para evitar "as any" se podria agregar una funcion flecha intermediaria.
onSubmit={(target)=> onAccept(target) }

2023-04-17 16:38 UTC, JavierAlbor commented on src/views/Technique/components/DeleteObjectiveDialog.tsx
> +import { useIntl } from 'react-intl'
Jerarquia de imp

2023-04-17 16:38 UTC, JavierAlbor commented on src/views/Technique/components/EvidenceList.tsx
> +          case 0:
Este case se podria omitir, ya que se define en el default

2023-04-17 16:38 UTC, JavierAlbor commented on src/views/Technique/index.tsx
> +/* eslint-disable @typescript-eslint/no-unused-vars */
No deberiamos omitir eslint rules

2023-04-17 16:46 UTC, Ghostramses commented on src/context/Technique/actions.ts
> +  const setTechnique = (payload: Technique): void => {
No sería mejor crear un action de limpieza y así llamarlo las veces necesarias sin necesidad de declararlas en cada sección?

2023-04-17 16:49 UTC, Ghostramses requested changes

2023-04-17 16:49 UTC, Ghostramses commented on src/views/Technique/index.tsx
Quitar el eslint-disable y corregir los problemas

2023-04-18 16:01 UTC, Ghostramses approved these changes

2023-04-18 16:02 UTC, merged